# Generated by Django 4.0.1 on 2022-01-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_persona_isstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='idNumber',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='lastname',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='picture',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
