# Generated by Django 4.0.1 on 2022-01-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_persona_isstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='phone',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
