# Generated by Django 4.0.1 on 2022-01-22 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_persona_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stafCheck', to='users.staffcheck'),
        ),
    ]
