# Generated by Django 4.0.1 on 2022-01-22 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_staffcheck_persona_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='isStaff',
        ),
    ]
