# Generated by Django 4.0.1 on 2022-01-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_persona_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='idNumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
