# Generated by Django 4.0.1 on 2022-01-16 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='turns.estados'),
        ),
        migrations.AddField(
            model_name='turnos',
            name='userStaff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userStaff', to='turns.estados'),
        ),
    ]
