# Generated by Django 4.0.1 on 2022-01-21 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_persona_isstaff'),
        ('turns', '0002_turnos_user_turnos_userstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='users.persona'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='userStaff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userStaff', to='users.persona'),
        ),
    ]
